package puppeteer;

import java.util.ArrayList;
import java.util.List;

public class CreaturePoseLibrary
{
	public static List<String> poseList = new ArrayList<>();
	public static List<String> poseStrings = new ArrayList<>();

	public static void addCreaturePose(String name, String poseString) {
		poseList.add(name);
		poseStrings.add(poseString);
	}
	static {
		 //default genetic poses as stolen from the chichi genome
		 addCreaturePose("none", "XXXXXXXXXXXXXXXX");
		 addCreaturePose("Reach low near", "??1312312010100X");
		 addCreaturePose("Reach lowish near", "??2212212010210X");
		 addCreaturePose("Reach highish near", "??22122121233XXX");
		 addCreaturePose("Reach high near", "??32102101233XXX");
		 addCreaturePose("Reach low medium", "?011121120111XXX");
		 addCreaturePose("Reach lowish medium", "?011121120112XXX");
		 addCreaturePose("Reach highish medium", "?121121101223XXX");
		 addCreaturePose("Reach high medium", "?221101100133XXX");
		 addCreaturePose("Reach low far", "?001121120222XXX");
		 addCreaturePose("Reach lowish far", "?021121120222XXX");
		 addCreaturePose("Reach highish far", "?221121121223XXX");
		 addCreaturePose("Reach high far", "?321101101233XXX");
		 addCreaturePose("Stand", "??2212122011210X");
		 addCreaturePose("Normal 1", "??2201122011100X");
		 addCreaturePose("Normal 2", "??2321000011101X");
		 addCreaturePose("Normal 3", "??2122201010102X");
		 addCreaturePose("Normal 4", "??2000321010000X");
		 addCreaturePose("Pained 1", "!01301122232331X");
		 addCreaturePose("Pained 2", "");
		 addCreaturePose("Pained 3", "");
		 addCreaturePose("Pained 4", "!01102122232300X");
		 addCreaturePose("Tired 1", "");
		 addCreaturePose("Tired 2", "");
		 addCreaturePose("Tired 3", "");
		 addCreaturePose("Tired 4", "");
		 addCreaturePose("Scared 1", "");
		 addCreaturePose("Scared 2", "");
		 addCreaturePose("Scared 3", "");
		 addCreaturePose("Scared 4", "");
		 addCreaturePose("Anger 1", "");
		 addCreaturePose("Anger 2", "");
		 addCreaturePose("Anger 3", "");
		 addCreaturePose("Anger 4", "");
		 addCreaturePose("To camera", "");
		 addCreaturePose("Express general need", "1121223011100XXX");
		 addCreaturePose("Express pain", "");
		 addCreaturePose("Express hunger", "");
		 addCreaturePose("Express tired", "");
		 addCreaturePose("Express lonely", "");
		 addCreaturePose("Express fear", "");
		 addCreaturePose("Toe tap 1", "");
		 addCreaturePose("Toe tap 2", "");
		 addCreaturePose("Angry 5", "");
		 addCreaturePose("Angry 6", "");
		 addCreaturePose("Swing arms 1", "");
		 addCreaturePose("Swing arms 2", "");
		 addCreaturePose("Shiver 1", "");
		 addCreaturePose("Shiver 2", "");
		 addCreaturePose("Slap Norn 1", "");
		 addCreaturePose("Retreat 1", "");
		 addCreaturePose("Retreat 2", "");
		 addCreaturePose("Retreat 3", "");
		 addCreaturePose("Retreat 4", "");
		 addCreaturePose("Flee 1", "!421011222222XXX");
		 addCreaturePose("Flee 2", "!422210002222XXX");
		 addCreaturePose("Flee 3", "!421221012222XXX");
		 addCreaturePose("Flee 4", "!120002212222XXX");
		 addCreaturePose("Rest", "??0301301020200X");
		 addCreaturePose("Sleep", "X003023020202XXX");
		 addCreaturePose("East", "??22122120112XXX");
		 addCreaturePose("West", "??22122120112XXX");
		 addCreaturePose("Bored 1", "?22201122011110X");
		 addCreaturePose("Bored 2", "?22321000001111X");
		 addCreaturePose("Bored 3", "?22122201001201X");
		 addCreaturePose("Bored 4", "?22000321010000X");
		 addCreaturePose("Throw 1", "");
		 addCreaturePose("Throw 2", "??31101103333XXX");
		 addCreaturePose("Kick 1", "");
		 addCreaturePose("Kick 2", "");
		 addCreaturePose("Drum 1", "?122212210133XXX");
		 addCreaturePose("Drum 2", "?132222220222XXX");
		 addCreaturePose("Sneeze 1", "");
		 addCreaturePose("Sneeze 2", "");
		 addCreaturePose("Eat 1", "?122122122222XXX");
		 addCreaturePose("Eat 2", "?222122121212XXX");
		 addCreaturePose("Startled", "?13001321011330X");
		 addCreaturePose("Kiss", "?221101102222XXX");
		 addCreaturePose("Dead", "?!0300300020200X");
		 addCreaturePose("Limp 1", "");
		 addCreaturePose("Limp 2", "");
		 addCreaturePose("Limp 3", "");
		 addCreaturePose("Limp 4", "");
		 addCreaturePose("Stagger 1", "");
		 addCreaturePose("Stagger 2", "");
		 addCreaturePose("Stagger 3", "");
		 addCreaturePose("Stagger 4", "");
		 addCreaturePose("Downhill 1", "");
		 addCreaturePose("Downhill 2", "");
		 addCreaturePose("Downhill 3", "");
		 addCreaturePose("Downhill 4", "");
		 addCreaturePose("Uphill 1", "");
		 addCreaturePose("Uphill 2", "");
		 addCreaturePose("Uphill 3", "");
		 addCreaturePose("Uphill 4", "");
		 addCreaturePose("Run 1 ", "");
		 addCreaturePose("Run 2", "");
		 addCreaturePose("Run 3", "");
		 addCreaturePose("Run 4", "");
		 addCreaturePose("Cough 1", "");
		 addCreaturePose("Cough 2", "");
		 addCreaturePose("Cough 3", "");
		 addCreaturePose("Cough 4", "");
		 addCreaturePose("Pushed 1", "");
		 addCreaturePose("Pushed 2", "");
		 addCreaturePose("Pushed 3", "");
		 addCreaturePose("Pushed 4", "");
		 addCreaturePose("Sneeze 3", "");
		 addCreaturePose("Lay Egg 1", "");
		 addCreaturePose("Lay Egg 2", "");
		 addCreaturePose("Lay Egg 3", "");
		 addCreaturePose("Lay Egg 4", "");
		 addCreaturePose("Slap Norn 2", "");
		 addCreaturePose("Slap Norn 3", "");
		 addCreaturePose("Slap Norn 4", "");
		 addCreaturePose("Slap Norn 5", "");
		 addCreaturePose("Falling 1", "");
		 addCreaturePose("Falling 2", "");
		 addCreaturePose("Impact 1", "");
		 addCreaturePose("Impact 2", "");
		 addCreaturePose("Impact 3", "");
		 addCreaturePose("Impact 4", "");
		 addCreaturePose("Impact 5", "");
		 addCreaturePose("Yawn 1", "");
		 addCreaturePose("Yawn 2", "");
		 addCreaturePose("Yawn 3", "");
		 addCreaturePose("Dance 1", "");
		 addCreaturePose("Dance 2", "");
		 addCreaturePose("Dance 3", "");
		 addCreaturePose("Dance 4", "");
		 addCreaturePose("Dance 5", "");
		 addCreaturePose("Dance 6", "");
		 addCreaturePose("Pushed behind 1", "");
		 addCreaturePose("Pushed behind 2", "");
		 addCreaturePose("Pushed behind 3", "");
		 addCreaturePose("Pushed behind 4", "");
		 addCreaturePose("Running 1", "");
		 addCreaturePose("Running 2", "");
		 addCreaturePose("Running 3", "");
		 addCreaturePose("Running 4", "");
		 addCreaturePose("Sexy 1", "");
		 addCreaturePose("Sexy 2", "");
		 addCreaturePose("Sexy 3", "");
		 addCreaturePose("Sexy 4", "");
		 addCreaturePose("Vomit 1", "");
		 addCreaturePose("Vomit 2", "");
		 addCreaturePose("Vomit 3", "");
		 addCreaturePose("Vomit 4", "");
		 addCreaturePose("Pick up 1", "");
		 addCreaturePose("Pick up 2", "");
		 addCreaturePose("Pick up 3", "");
		 addCreaturePose("Pick up 4", "");
		 addCreaturePose("Creep 1", "");
		 addCreaturePose("Creep 2", "");
		 addCreaturePose("Creep 3", "");
		 addCreaturePose("Creep 4", "");
		 addCreaturePose("Creep 5", "");
		 addCreaturePose("Jive 1", "");
		 addCreaturePose("Jive 2", "");
		 addCreaturePose("Jive 3", "");
		 addCreaturePose("Jive 4", "");
		 addCreaturePose("Jive 5", "");
		 addCreaturePose("Vomit 5", "");
		 addCreaturePose("Teeter 1", "");
		 addCreaturePose("Teeter 2", "");
		 addCreaturePose("Teeter 3", "");
		 addCreaturePose("Teeter 4", "");
		 addCreaturePose("Teeter 5", "");
		 addCreaturePose("Totter 1", "");
		 addCreaturePose("Totter 2", "");
		 addCreaturePose("Totter 3", "");
		 addCreaturePose("Totter 4", "");
		 addCreaturePose("Reward", "");
		 addCreaturePose("Punishment", ""); 
	 }
	
	

}
